#!/usr/bin/env python3
"""Module that generates a detailed classification report."""
from sklearn import metrics


def evaluate(true_labels, predicted_labels, class_names):
    """
    Generate a detailed classification report using Scikit-learn.

    Args:
        true_labels: Ground truth labels.
        predicted_labels: Predicted labels.
        class_names: List of class names corresponding to the label
            indices.

    Returns:
        A string containing the classification report generated by
        Scikit-learn.
    """
    report = metrics.classification_report(
        true_labels, predicted_labels, target_names=class_names)
    return report
